# Generated by Django 4.0.4 on 2022-05-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='apellido materno')),
                ('nombres', models.CharField(max_length=20, verbose_name='Nombre')),
                ('fecha_nacimeinto', models.DateField(verbose_name='fecha de nacimeiento')),
                ('sexo', models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.docente'),
        ),
    ]
